sudo: false
language: python
python:

    - '2.6'
    - '2.7'
    - '3.3'
    - '3.4'
    - '3.5'
    - '3.6-dev'
    - pypy
    - nightly
# command to install dependencies
install: "pip install -U tox"
# # command to run tests
env:
  matrix:
    - TOXENV=py-pytest28
    - TOXENV=py-pytest29
    - TOXENV=py-pytest30
matrix:
  include:
    - python: '2.7'
      env: TOXENV=check
    - python: '3.5'
      env: TOXENV=check
script:
 - tox --recreate -e $TOXENV

notifications:
  irc:
    channels:
      - "chat.freenode.net#pytest"
    on_success: change
    on_failure: change
    skip_join: true
#  email:
#    - pytest-commit@python.org
